[config.wallpaper]
command = "swww query"
set = false

[templates.hyprland]
input_path = '/home/deval/.config/matugen/templates/hyprland-colors.conf'
output_path = '/home/deval/.config/hypr/colors.conf'

[templates.kitty]
input_path = '/home/deval/.config/matugen/templates/kitty-colors.conf'
output_path = '/home/deval/.config/kitty/colors.conf'

[templates.waybar]
input_path = '/home/deval/.config/matugen/templates/colors.css'
output_path = '/home/deval/.config/waybar/colors.css'

[templates.wofi]
input_path = '/home/deval/.config/matugen/templates/wofi-colors.css'
output_path = '/home/deval/.config/wofi/colors.css'

[templates.gtk]
input_path = '/home/deval/.config/matugen/templates/gtk-colors.css'
output_path = '/home/deval/.config/gtk-3.0/colors.css'

[templates.rofi]
input_path = '/home/deval/.config/matugen/templates/rofi-colors.rasi'
output_path = '/home/deval/.config/rofi/colors.rasi'

[templates.ags]
input_path = '/home/deval/.config/matugen/templates/ags-colors.css'
output_path = '/home/deval/.config/ags/colors.css'
