-- WezTerm Dynamic Colors - Generated by Matugen
return {
  foreground = "{{ colors.on_surface.default.hex }}",
  background = "{{ colors.surface.default.hex }}",
  
  cursor_bg = "{{ colors.primary.default.hex }}",
  cursor_fg = "{{ colors.on_primary.default.hex }}",
  cursor_border = "{{ colors.primary.default.hex }}",
  
  selection_fg = "{{ colors.on_primary_container.default.hex }}",
  selection_bg = "{{ colors.primary_container.default.hex }}",
  
  scrollbar_thumb = "{{ colors.outline.default.hex }}",
  split = "{{ colors.outline_variant.default.hex }}",
  
  ansi = {
    "{{ colors.surface_dim.default.hex }}",
    "{{ colors.error.default.hex }}",
    "{{ colors.tertiary.default.hex }}",
    "{{ colors.secondary.default.hex }}",
    "{{ colors.primary.default.hex }}",
    "{{ colors.tertiary_container.default.hex }}",
    "{{ colors.secondary_container.default.hex }}",
    "{{ colors.on_surface.default.hex }}",
  },
  
  brights = {
    "{{ colors.surface_container_high.default.hex }}",
    "{{ colors.error_container.default.hex }}",
    "{{ colors.tertiary.default.hex }}",
    "{{ colors.secondary.default.hex }}",
    "{{ colors.primary.default.hex }}",
    "{{ colors.tertiary_container.default.hex }}",
    "{{ colors.secondary_container.default.hex }}",
    "{{ colors.on_surface_variant.default.hex }}",
  },
  
  tab_bar = {
    background = "{{ colors.surface.default.hex }}",
    active_tab = {
      bg_color = "{{ colors.primary_container.default.hex }}",
      fg_color = "{{ colors.on_primary_container.default.hex }}",
    },
    inactive_tab = {
      bg_color = "{{ colors.surface_container.default.hex }}",
      fg_color = "{{ colors.on_surface_variant.default.hex }}",
    },
    inactive_tab_hover = {
      bg_color = "{{ colors.surface_container_high.default.hex }}",
      fg_color = "{{ colors.on_surface.default.hex }}",
    },
    new_tab = {
      bg_color = "{{ colors.surface_container.default.hex }}",
      fg_color = "{{ colors.on_surface.default.hex }}",
    },
  },
}
